# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - bumpless
    ignore:
      # gdal version is dictated by https://github.com/lambgeo/docker-lambda, currently 3.8.3
      - dependency-name: gdal
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - bumpless
