version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
    - pip3 install -r reformat/requirements.txt -t reformat/src/
    - sed "s/REPLACE_ME/$(openssl rand -hex 4)/" cloudformation.yaml > cloudformation-replaced.yaml
    - aws cloudformation package --template-file cloudformation-replaced.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml
artifacts:
  type: zip
  files:
  - cloudformation-final.yaml
