AWSTemplateFormatVersion: 2010-09-09

Parameters:

  LogBucket:
    Type: String

  LogPrefix:
    Type: String
    Default: aws-s3-access/

  StorageExpirationInDays:
    Type: Number
    MinValue: 1
    Default: 7

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 1
        - Status: Enabled
          ExpirationInDays: !Ref StorageExpirationInDays
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: !Sub "${LogPrefix}${AWS::StackName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub "${Bucket.Arn}/*"
