AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  Bucket:
    Type: String

  ProductPath:
    Type: String

  GdalLayerArn:
    Type: String

  GdalDataPath:
    Type: String
    Default: /opt/lib/data

Outputs:

  LambdaArn:
    Value: !GetAtt Lambda.Arn

Resources:

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Name}-dlq"
      MessageRetentionPeriod: 1209600

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Name}"
      RetentionInDays: 30

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Name
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !GetAtt LogGroup.Arn
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt DeadLetterQueue.Arn
          - Effect: Allow
            Action: s3:PutObject
            Resource: "arn:aws:s3:::${Bucket}/*"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref Name
      Code: src/
      DeadLetterConfig:
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          CONFIG: !Sub |-
            {
              "bucket": "${Bucket}",
              "product_path": "${ProductPath}"
            }
          GDAL_DATA: !Ref GdalDataPath
          CPL_VSIL_CURL_CHUNK_SIZE: 10485760
          GDAL_HTTP_COOKIEFILE: /tmp/cookies.txt
          GDAL_HTTP_COOKIEJAR: /tmp/cookies.txt
      Handler: main.lambda_handler
      Layers:
      - !Ref GdalLayerArn
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python2.7
      Timeout: 30
