name: Deploy to production

on:
  push:
    branches:
      - prod

concurrency: deploy-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          STACK_NAME: gdal-api-prod
          LOG_BUCKET: grfn-logs
          LOG_PREFIX: s3-access/
          STORAGE_EXPIRATION_IN_DAYS: 1
          PRODUCT_PATH: https://grfn.asf.alaska.edu/door/download/
          URS_HOSTNAME: urs.earthdata.nasa.gov
          URS_USERNAME: ${{ secrets.URS_USERNAME }}
          URS_PASSWORD: ${{ secrets.URS_PASSWORD }}
          DOMAIN_NAME: services.asf.alaska.edu
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
