name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.11.2
    with:
      release_prefix: GRFN GDAL API
      release_branch: prod
      develop_branch: test
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
