name: Static code analysis

on: push

jobs:

  call-ruff-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-ruff.yml@v0.17.1

  call-mypy-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-mypy.yml@v0.17.1

  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint --info --ignore-checks W3002 --template **/cloudformation.yml
